### ISSUE TITLE
Please modify the 'to_pandassql' method to accept sqlalchemy 'create_engine' optional parameters like 'encoding', 'convert_unicode' and others

### ISSUE THREAD

**Issue by AlexandrPaveluc** [rnelsonchem/simpledbf#3]
Hi! Thank you for great project.

**Comment by rnelsonchem** [comment]
@AlexandrPaveluc I updated the method to accept either a string (as before) or a SQLAlchemy engine instance. That means you should be able to do any sort of fancy engine creation and then pass that to the to_pandassql method. This is only in the master, so you'll have to install from git. Let me know if it works. 

I updated the doc string for the method, but not the documentation. I'll create a new release if everything is okay.

**Comment by AlexandrPaveluc** [comment]
Thanks!
