### ISSUE TITLE
Strange assertion in simpledbf.py line 564

### ISSUE THREAD

**Issue by AlexandrPaveluc** [rnelsonchem/simpledbf#4]
Could you explain me the meaning of this portion of code? I got this AssertionError and don't why... Is the dbf file corupt?

```
terminator = self.f.read(1)
assert terminator == b'\r'
```

**Comment by rnelsonchem** [comment]
Hmmm... That assertion is a leftover from the original activestate code. I've never had a dbf file throw that assertion error, so I've never needed to investigate. Did you try commenting it out? If it works, I would check the output relative to the original data. LibreOffice can open and save dbf files.

**Comment by AlexandrPaveluc** [comment]
Hi. I was bulk processing a directory with dbf files.Checked the dbf file  which triggered AssertionError - all rows are marked as deleted.

**Comment by rnelsonchem** [comment]
Okay. That is good information. I may change the assertion to a raise and error instead. I'll add a note to check the contents of the DBF. 

So things are okay with all other files. Yes? Or is there still an issue here.

**Comment by AlexandrPaveluc** [comment]
With other files this error doesn't appear.

**Comment by rnelsonchem** [comment]
Glad it worked for the others. Thanks for the pointing out these issues.
